# Box baseline
---
tasks:
  homebrew:
    formulas:
    - wget
    - ansible
    - bash-completion
    - git
    - htop-osx
    - midnight-commander
    - mtr
    - node
    - python
    - readline
    - ssh-copy-id
    - the_silver_searcher
    - tree
    - watch
    - wget
    - shellcheck
  gem:
    packages:
    - bundler
    - fpm
    - pry
    - pry-nav
    - rubocop
    - rspec
    - mdl
  pip:
    packages:
    - docopt
    - pylint
  dotfiles:
    repo: miguelcnf/dotfiles
    list:
    - .vimrc
    - .rspec
    - .gitconfig
    - .bash_profile
    - .ansible.cfg
    - .mavenrc
  pathogen:
    plugins:
      - { repo: 'mhinz/vim-signify', name: 'vim-signify' }
      - { repo: 'mhinz/vim-startify', name: 'vim-startify' }
      - { repo: 'chrisbra/Recover.vim', name: 'recover' }
      - { repo: 'vim-scripts/TaskList.vim', name: 'tasklist' }
      - { repo: 'epmatsw/ag.vim', name: 'ag' }
      - { repo: 'Raimondi/delimitMate', name: 'delimitmate' }
      - { repo: 'othree/javascript-libraries-syntax.vim', name: 'javascript-libraries-syntax' }
      - { repo: 'scrooloose/nerdtree', name: 'nerdtree' }
      - { repo: 'ervandew/supertab', name: 'supertab' }
      - { repo: 'scrooloose/syntastic', name: 'syntastic' }
      - { repo: 'bling/vim-airline', name: 'vim-airline' }
      - { repo: 't9md/vim-chef', name: 'vim-chef' }
      - { repo: 'tpope/vim-fugitive', name: 'vim-fugitive' }
      - { repo: 'pangloss/vim-javascript', name: 'vim-javascript' }
      - { repo: 'elzr/vim-json', name: 'vim-json' }
      - { repo: 'altercation/vim-colors-solarized', name: 'vim-colors-solarized' }
      - { repo: 'tpope/vim-surround.git', name: 'vim-surround' }

